### ISSUE TITLE
Icon doesn't shows

### ISSUE THREAD

**Issue by ikorich** [dagronf/DSFDropFilesView#1]
hi there,

you have issue for icon on this line:
https://github.com/dagronf/DSFDropFilesView/blob/9819b2c2711de63bb8c5f7835d4012f2fe0aad85/Sources/DSFDropFilesView/DSFDropFilesView%2BSwiftUI.swift#L173

should be
`showIcon = (nsView.icon != nil)`

if update icon on fly it hides

**Comment by dagronf** [comment]
Ah thank you! I don't know how I overlooked that one.

I've updated the code - if you use the 3.1.1 tag you'll see your fix in there.
