### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by DevulderJeanPaul** [dagronf/DSFDropFilesView#2]
hi,

let dp = DSFDropFilesView()
              
dp.label = "Select a directory..."

have a error:

 'label' is inaccessible due to 'internal' protection level

it's my code ?

thanks,

// Xcode 14.3.1 & command line tools 14.3.1

**Comment by dagronf** [comment]
Hi @DevulderJeanPaul, apologies for that!

I've been calling these methods dynamically via interface builder and interestingly I've never picked up this visibility issue when creating a `DSFDropFilesView` object directly!

If you update to the latest version (3.2.0) the problem should be fixed.  Please let me know how you go.

**Comment by DevulderJeanPaul** [comment]
Hi,
It's working.
Thanks,
