### ISSUE TITLE
Error with MacOS version

### ISSUE THREAD

**Issue by sujee81** [dagronf/DSFDropFilesView#3]
Hi,
Thanks for implementing this package. I'm new to MacOS development. When I tried to add this to my MacOS app with deployment target 13, I get the following error

`'CAMediaTimingFunctionName' is only available in MacOS 10.14 or newer`

I noticed that the package.swift has the target as MacOS 10.11 instead of 11.14.

```
platforms: [
   .macOS(.v10_11)
],
```

I tried to correct this in my own copy of DSFDropFilesView but I get different error. I'm new to building a package so I could be missing something (https://github.com/sujee81/DSFDropFilesView).

The new error I get in my own copy of the package is

`no such file or directory: '/Users/sujee/Library/Developer/Xcode/DerivedData/MyApp-xxxxxxx/Build/Products/Debug/PackageFrameworks/DSFDropFilesView-shared.framework/Versions/A/DSFDropFilesView-shared'`

**Comment by dagronf** [comment]
@sujee81  Hey mate -- sorry you're having issues.  I'm having troubles reproducing the issues you're seeing locally.

I've just pushed up a new version (4.0.1) which drops support for 10.11/10.12 and (I think) may fix the issue -- there's some oddness with the pre-10.14 api in the later Xcode versions. Can you try this new version out and see if it fixes the issue?

Many thanks -- Darren.

**Comment by sujee81** [comment]
Thanks Darren for quick response. The first issue I mentioned is now resolved. However the second issue still there. Previously I used the new Xcode 16-beta. I thought it could be the issue. But when I created a sample project with Xcode 15.4 and tried to add the library, I still get the error. Looks like something specific to my setup. Attached some screenshots. Any help appreciated. 
<img width="1488" alt="image" src="https://github.com/dagronf/DSFDropFilesView/assets/659991/157e9b6f-bdae-4646-bccb-d0ab55857da5">
<img width="598" alt="image" src="https://github.com/dagronf/DSFDropFilesView/assets/659991/11854326-dc14-41f7-b867-4d5c2497c2d0">
<img width="1487" alt="image" src="https://github.com/dagronf/DSFDropFilesView/assets/659991/0d78d547-0dfa-4ccb-9204-01b529849899">

**Comment by dagronf** [comment]
Hi @sujee81,

I'm guessing you've got an issue with the linking to the library.  It appears you're trying to use the shared framework, so make sure that you're linking correctly.

Check that your "Frameworks, Libraries, and Embedded Content" looks something like this :-

<img width="1012" alt="image" src="https://github.com/dagronf/DSFDropFilesView/assets/2636615/a081e66d-70bd-4cdd-805d-918328f0079c">

When using a shared component, you'll need to copy it into the application you're building, along with signing it etc.  

I've attached a sample project using Xcode 15.4 that (I think) should mirror what you're trying to do

[testdsf2.zip](https://github.com/user-attachments/files/16141158/testdsf2.zip)

Can you try building this project and see if it works?

Cheers -- Darren.

**Comment by sujee81** [comment]
Hi @dagronf 
It did the trick. I will read more about working with libraries in Swift projects. Thanks for taking time to look into it. Really appreciate it.
