### ISSUE TITLE
My app is crashing immediately.

### ISSUE THREAD

**Issue by deckyboiii** [dagronf/DSFDropFilesView#4]
I'm not exactly sure what is happening, but I have a screenshot of my code, and what Xcode opens when the app crashes.

![Screenshot 2024-07-19 at 10 25 52 PM](https://github.com/user-attachments/assets/72b7a533-faf3-4031-8864-0d2b88e54e79)
![Screenshot 2024-07-19 at 10 26 07 PM](https://github.com/user-attachments/assets/231d8e72-1778-4a3c-99d2-b519f743d4a0)

Help would be greatly appreciated :)

**Comment by dagronf** [comment]
Hi @Declan-Reid 

Check [this recent closed issue](https://github.com/dagronf/DSFDropFilesView/issues/3#issuecomment-2217140960) comment and try out the attached project to see if it builds and runs.

If not, you'll need to give me more information -- which Xcode version? which macOS version? Are you trying to link against the static library or as a framework? 

Is it possible to attach the project which is failing so I can try it here? If not, can you create a new minimal project that shows the issue and attach it?

**Comment by deckyboiii** [comment]
Hi @dagronf

I tried the project you suggested, but it results in the same error.

As for some information, I'm using Xcode 16.0.0 Beta (Most likely the cause), MacOS 14.5, and I'm not quite sure what the third question is talking about.

The project I have made so far is as minimal as can be, so I'll attach it [here](https://github.com/user-attachments/files/16318909/Sanitizer.zip)

Thanks!

**Comment by dagronf** [comment]
Okay I can reproduce it.  Something has changed in Xcode 16 beta regarding the reduce motion setting.  How annoying!

Lemme see what I can do about it...

**Comment by dagronf** [comment]
Okay, I have a workaround for the Xcode 16 build weirdness. Its a bit weird - Apple has deprecated `AXAnimatedImagesEnabled` for macOS 15 (which is fine), but Xcode 16 appears to have dropped the symbol completely from its builds which means that apps built with Xcode 16 BUT TARGET macOS 14 now crash. It's quite puzzling.

Anyway, I've worked around the issue, so if you update the version of DSFDropFilesView to 4.1.0 in your project it now works as expected.

Please let me know how you go.

<img width="925" alt="image" src="https://github.com/user-attachments/assets/825aed4e-dc76-4c75-8075-60083c54c770">

**Comment by deckyboiii** [comment]
Success! Thank you very much!
