### ISSUE TITLE
DSFDropView-shared issue

### ISSUE THREAD

**Issue by stevenanthonyrevo** [dagronf/DSFDropFilesView#5]
Hi, 

Great Lib!

I've had an issue trying to install the package the latest.  

```
No such file or directory: /PackageFrameworks/DSFDropFilesView-shared.framework/Versions/A/DSFDropFilesView-shared
```

```
No such file or directory: /PackageFrameworks/DSFDropFilesViewDynamic.framework/Versions/A/DSFDropFilesViewDynamic
``` 

If anyone else had similar issues loading package, Version 3.0 works great!

**Comment by dagronf** [comment]
Hi @stevenanthonyrevo,

The name of the dynamic library was changed from 'DSFDropFilesViewDynamic' to 'DSFDropFilesView-shared' in order to bring the naming in line with the other projects I have.

Make sure that when you upgrade you change the `Frameworks, Libraries and Embedded Content` to contain the new dynamic library `DSFDropFilesView-shared` instead.

<img width="855" alt="Screenshot 2024-12-18 at 10 06 29 am" src="https://github.com/user-attachments/assets/89f0cb1e-f3b4-4d1d-9849-313d5bdf25e0" />

Let me know how you go

**Comment by stevenanthonyrevo** [comment]
@dagronf Thanks for getting back to me so quickly!

 I did load the library with`embed & sign`and tried to load version 4.0 but wasn't able to get past the missing directory even with those changes. 

The only setup that works for me is include local package version 3.0 and including the DropFilesView.

![Screenshot 2024-12-20 at 3 29 25 PM](https://github.com/user-attachments/assets/e06fb9da-7eb2-48d8-88ca-47ab86f303e8)

![Screenshot 2024-12-20 at 3 31 16 PM](https://github.com/user-attachments/assets/6225e789-dcf0-465f-a10d-1e0485b376ee)

**Comment by dagronf** [comment]
@stevenanthonyrevo Can you please create and attach a simple Xcode project that shows the issue?  I don't have enough information to reproduce your issue here.

**Comment by dagronf** [comment]
Here's a new macOS project, brand new, I added `DSFDropFilesView` version `4.1.0`. Can you try opening the project and see if it works on your machine?

<img width="1376" alt="image" src="https://github.com/user-attachments/assets/5c1962c1-35bd-4a5e-8e96-078fd6e8d96c" />

<img width="909" alt="image" src="https://github.com/user-attachments/assets/299898f5-455d-4df9-bbb8-8e76239947f1" />

<img width="427" alt="image" src="https://github.com/user-attachments/assets/4ee61afd-ef03-4197-8e62-18c4decd410d" />

[dropfilesviewtest.zip](https://github.com/user-attachments/files/18217279/dropfilesviewtest.zip)

**Comment by stevenanthonyrevo** [comment]
Hi @dagronf 

I tried opening the test but got an different error. 

![Screenshot 2024-12-21 at 12 57 40 AM](https://github.com/user-attachments/assets/5a8d9c24-926e-4bbb-91fb-5739dd37adfb)

I then tried to just start a fresh Xcode project named Sample. 

[DSFDropView-MacOS-Sample.zip](https://github.com/user-attachments/files/18217415/DSFDropView-MacOS-Sample.zip)

I added in the code to utilize the library and I see the error. 

![Screenshot 2024-12-21 at 1 00 12 AM](https://github.com/user-attachments/assets/1df06dbf-10d3-4649-832d-eac35043292d)

![Screenshot 2024-12-21 at 12 59 52 AM](https://github.com/user-attachments/assets/df5068fb-39b8-4e8d-b3cd-a40970d06627)

```
No such file or directory: '/Library/Developer/Xcode/DerivedData/sample/Build/Intermediates.noindex/Previews/sample/Products/Debug/PackageFrameworks/DSFDropFilesView-shared.framework/Versions/A/DSFDropFilesView-shared'
```

Try out the Sample zip folder to see if I'm missing something? 

I'm glad.. I did get it working with an earlier version, As soon as I try the latest version I get stuck on the same compile error.

**Comment by stevenanthonyrevo** [comment]
Here's the version of Xcode I'm using Version 15.2 and another image for how I'm implementing into the content view. 
![Screenshot 2024-12-21 at 1 07 34 AM](https://github.com/user-attachments/assets/e2f8c32a-5dc5-42c3-a5ad-af4f7e96c7e3)

**Comment by dagronf** [comment]
I added `DSFDropFilesView` to your project and ran it fine

<img width="1012" alt="Screenshot 2024-12-21 at 5 11 10 pm" src="https://github.com/user-attachments/assets/c5de5dea-4f7f-4207-b48a-7da72f6cf426" />

**Comment by dagronf** [comment]
Here's the updated project.

[DSFDropView-MacOS-Sample 2.zip](https://github.com/user-attachments/files/18217457/DSFDropView-MacOS-Sample.2.zip)

**Comment by stevenanthonyrevo** [comment]
Awesome! I just installed the updated project and it works. May I ask what is different?

**Comment by dagronf** [comment]
> Here's the version of Xcode I'm using Version 15.2 and another image for how I'm implementing into the content view. ![Screenshot 2024-12-21 at 1 07 34 AM](https://private-user-images.githubusercontent.com/8505293/397908443-e2f8c32a-5dc5-42c3-a5ad-af4f7e96c7e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3NjE4MDIsIm5iZiI6MTczNDc2MTUwMiwicGF0aCI6Ii84NTA1MjkzLzM5NzkwODQ0My1lMmY4YzMyYS01ZGM1LTQyYzMtYTVhZC1hZjRmN2U5NmM3ZTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjFUMDYxMTQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzcxMjIzZGZhZTE0MTIzODE2Y2JhOWExOTY0NjBjYjJiZWI3NjUzODVkYzE0ZWI0NTMwMDI2NTU2YWVkY2IwZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.cBr0wEaVOCMYsZH2aC7-jpI6GtI-4_fvKibTLQCofvg)

This is a derived data issue. You might just need to clean the build projects. `Menu` > `Project` > `Clean Build Folder...`

**Comment by stevenanthonyrevo** [comment]
Awesome, Thanks so much!

**Comment by dagronf** [comment]
> Awesome! I just installed the updated project and it works. May I ask what is different?

All I did was add `DSFDropFilesView` to the project as described above. I am using Xcode 16 tho 🤔

**Comment by stevenanthonyrevo** [comment]
Okay maybe it was the embeds still messing me up. 

This works. 
![Screenshot 2024-12-21 at 1 21 53 AM](https://github.com/user-attachments/assets/27dfd567-3fe4-43a8-9e8c-496d70291435)

This didn't. 
![Screenshot 2024-12-21 at 12 49 32 AM](https://github.com/user-attachments/assets/39928172-b2b2-4f9c-94f5-e7455fd57fcd)

**Comment by dagronf** [comment]
You only need to add one in the 'Frameworks, Libraries and Embedded Content' section or else you'll get weirdness.

DSFDropFilesView -> static library
DSFDropFilesView-shared -> dynamic library
DSFDropFilesView-static -> static library (same as the first one, just renamed)

All of these are the SAME library just in different forms.  Some folks want to use Dynamic libraries (which can be shared between multiple targets to reduce code size) and others want a static library which simplifies things but makes the overall app size bigger in some situations.

As a result, you only need to add ONE of these.  If you're not sure which one you want, choose `DSFDropFilesView`.,

**Comment by stevenanthonyrevo** [comment]
I'm finally able to use latest version of `DSFDropFilesView ` library for macOS development. That makes sense now, thank you for the explanation and assistance!
